[package]
name = "keys_and_derivation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0" 
sha2 = "0.10.6"
hmac = "0.12.1"
hex-literal = "0.3.4"